name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.1d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98346a45486f4b43180f1011938d9d5ce1ccd7b5c8f98038e3aecb69c32fd051"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
