name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.3h"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b47947276fa795a0eb610ffd7c3ab89c503a360c7ee3cd11f204283e07ccdca9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
