name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.1c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efdc02b9e40472c1c1a27de6ed93c5b6a67965446c34e61f7b39338a9ba2a1a0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
