name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.3h"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13522bd73d83ae3ea13f39c06bc42729f91677527bd700df452ae7ee901def51"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
