name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.3d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef44b61f0f5452786b1c79df698265c6d2d72cf6cba4e3886b0d91b93c9c291b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
