name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.1d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ace199acf35bb2fc34561fdcfc7ad907d0c431c37844f3e9f9fa43db515315"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
