name = "Modpack Serwer 2et"
author = "Nikodem T"
version = "0.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be525700f4fa2e0e86a3a396408c6db75e2390da20fd377a344d0254fa649955"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
